-- ----------------------------
-- View structure for vu_detail_jual_paket
-- ----------------------------
CREATE  OR REPLACE VIEW `vu_detail_jual_paket` AS select `detail_jual_paket`.`dpaket_master` AS `dpaket_master`,`detail_jual_paket`.`dpaket_paket` AS `dpaket_paket`,`vu_paket`.`paket_nama` AS `produk_nama`,`vu_paket`.`kategori2_nama` AS `kategori2_nama`,`detail_jual_paket`.`dpaket_jumlah` AS `jumlah_barang`,`detail_jual_paket`.`dpaket_harga` AS `harga_satuan`,`detail_jual_paket`.`dpaket_diskon` AS `dpaket_diskon`,`detail_jual_paket`.`dpaket_diskon_jenis` AS `diskon_jenis`,`detail_jual_paket`.`dpaket_sales` AS `sales`,`master_jual_paket`.`jpaket_nobukti` AS `no_bukti`,`master_jual_paket`.`jpaket_cust` AS `jpaket_cust`,`customer`.`cust_member` AS `cust_member`,`customer`.`cust_nama` AS `cust_nama`,`customer`.`cust_no` AS `cust_no`,`customer`.`cust_kelamin` AS `cust_kelamin`,`customer`.`cust_alamat` AS `cust_alamat`,`customer`.`cust_kota` AS `cust_kota`,`vu_paket`.`paket_kode` AS `produk_kode`,_utf8'paket' AS `satuan_nama`,`detail_jual_paket`.`dpaket_diskon` AS `diskon`,(((`detail_jual_paket`.`dpaket_harga` * `detail_jual_paket`.`dpaket_jumlah`) * `detail_jual_paket`.`dpaket_diskon`) / 100) AS `diskon_nilai`,((`detail_jual_paket`.`dpaket_harga` * `detail_jual_paket`.`dpaket_jumlah`) - (((`detail_jual_paket`.`dpaket_harga` * `detail_jual_paket`.`dpaket_jumlah`) * `detail_jual_paket`.`dpaket_diskon`) / 100)) AS `subtotal`,`master_jual_paket`.`jpaket_tanggal` AS `tanggal`,`customer`.`cust_id` AS `cust_id` from (((`detail_jual_paket` join `vu_paket` on((`vu_paket`.`paket_id` = `detail_jual_paket`.`dpaket_paket`))) join `master_jual_paket` on((`detail_jual_paket`.`dpaket_master` = `master_jual_paket`.`jpaket_id`))) join `customer` on((`master_jual_paket`.`jpaket_cust` = `customer`.`cust_id`)));

-- ----------------------------
-- View structure for vu_detail_jual_produk
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_detail_jual_produk` AS select `detail_jual_produk`.`dproduk_id` AS `dproduk_id`,`detail_jual_produk`.`dproduk_produk` AS `dproduk_produk`,`detail_jual_produk`.`dproduk_satuan` AS `dproduk_satuan`,`detail_jual_produk`.`dproduk_jumlah` AS `jumlah_barang`,`detail_jual_produk`.`dproduk_harga` AS `harga_satuan`,`detail_jual_produk`.`dproduk_diskon` AS `diskon`,`detail_jual_produk`.`dproduk_diskon_jenis` AS `diskon_jenis`,`detail_jual_produk`.`dproduk_sales` AS `sales`,`master_jual_produk`.`jproduk_nobukti` AS `no_bukti`,`master_jual_produk`.`jproduk_tanggal` AS `tanggal`,`customer`.`cust_id` AS `cust_id`,`customer`.`cust_no` AS `cust_no`,`customer`.`cust_member` AS `cust_member`,`customer`.`cust_nama` AS `cust_nama`,`customer`.`cust_kelamin` AS `cust_kelamin`,`customer`.`cust_alamat` AS `cust_alamat`,`customer`.`cust_kota` AS `cust_kota`,`vu_produk`.`produk_kode` AS `produk_kode`,`vu_produk`.`produk_kategori` AS `produk_kategori`,`vu_produk`.`produk_kontribusi` AS `produk_kontribusi`,`vu_produk`.`produk_nama` AS `produk_nama`,`vu_produk`.`produk_satuan` AS `produk_satuan`,`vu_produk`.`produk_du` AS `produk_du`,`vu_produk`.`produk_dm` AS `produk_dm`,`vu_produk`.`produk_point` AS `produk_point`,`vu_produk`.`produk_harga` AS `produk_harga`,`vu_produk`.`produk_volume` AS `produk_volume`,`vu_produk`.`produk_jenis` AS `produk_jenis`,`satuan`.`satuan_nama` AS `satuan_nama`,(((`detail_jual_produk`.`dproduk_harga` * `detail_jual_produk`.`dproduk_diskon`) / 100) * `detail_jual_produk`.`dproduk_jumlah`) AS `diskon_nilai`,((`detail_jual_produk`.`dproduk_harga` * `detail_jual_produk`.`dproduk_jumlah`) - (((`detail_jual_produk`.`dproduk_harga` * `detail_jual_produk`.`dproduk_diskon`) / 100) * `detail_jual_produk`.`dproduk_jumlah`)) AS `subtotal`,`master_jual_produk`.`jproduk_id` AS `jproduk_id` from ((((`detail_jual_produk` join `master_jual_produk` on((`detail_jual_produk`.`dproduk_master` = `master_jual_produk`.`jproduk_id`))) join `customer` on((`master_jual_produk`.`jproduk_cust` = `customer`.`cust_id`))) join `vu_produk` on((`vu_produk`.`produk_id` = `detail_jual_produk`.`dproduk_id`))) join `satuan` on((`detail_jual_produk`.`dproduk_satuan` = `satuan`.`satuan_id`)));

-- ----------------------------
-- View structure for vu_detail_jual_rawat
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_detail_jual_rawat` AS select `detail_jual_rawat`.`drawat_master` AS `drawat_master`,`detail_jual_rawat`.`drawat_rawat` AS `drawat_rawat`,`vu_perawatan`.`rawat_nama` AS `produk_nama`,`vu_perawatan`.`kategori2_nama` AS `kategori2_nama`,`vu_perawatan`.`kategori_nama` AS `kategori_nama`,`vu_perawatan`.`jenis_nama` AS `jenis_nama`,`detail_jual_rawat`.`drawat_jumlah` AS `jumlah_barang`,`detail_jual_rawat`.`drawat_harga` AS `harga_satuan`,`detail_jual_rawat`.`drawat_diskon` AS `drawat_diskon`,`detail_jual_rawat`.`drawat_diskon_jenis` AS `diskon_jenis`,`detail_jual_rawat`.`drawat_sales` AS `sales`,`master_jual_rawat`.`jrawat_nobukti` AS `no_bukti`,`master_jual_rawat`.`jrawat_cust` AS `jrawat_cust`,`customer`.`cust_member` AS `cust_member`,`customer`.`cust_nama` AS `cust_nama`,`customer`.`cust_no` AS `cust_no`,`customer`.`cust_kelamin` AS `cust_kelamin`,`customer`.`cust_alamat` AS `cust_alamat`,`customer`.`cust_kota` AS `cust_kota`,`vu_perawatan`.`rawat_kode` AS `produk_kode`,_utf8'paket' AS `satuan_nama`,`detail_jual_rawat`.`drawat_diskon` AS `diskon`,(((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) * `detail_jual_rawat`.`drawat_diskon`) / 100) AS `diskon_nilai`,((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) - (((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) * `detail_jual_rawat`.`drawat_diskon`) / 100)) AS `subtotal`,`master_jual_rawat`.`jrawat_tanggal` AS `tanggal`,`customer`.`cust_id` AS `cust_id` from (((`detail_jual_rawat` join `vu_perawatan` on((`vu_perawatan`.`rawat_id` = `detail_jual_rawat`.`drawat_rawat`))) join `master_jual_rawat` on((`detail_jual_rawat`.`drawat_master` = `master_jual_rawat`.`jrawat_id`))) join `customer` on((`master_jual_rawat`.`jrawat_cust` = `customer`.`cust_id`)));

-- ----------------------------
-- View structure for vu_detail_order_beli
-- ----------------------------
CREATE  OR REPLACE VIEW `vu_detail_order_beli` AS select `supplier`.`supplier_nama` AS `supplier_nama`,`supplier`.`supplier_alamat` AS `supplier_alamat`,`supplier`.`supplier_kota` AS `supplier_kota`,`supplier`.`supplier_akun` AS `supplier_akun`,`master_order_beli`.`order_supplier` AS `order_supplier`,`master_order_beli`.`order_tanggal` AS `order_tanggal`,`master_order_beli`.`order_carabayar` AS `order_carabayar`,`master_order_beli`.`order_diskon` AS `order_diskon`,`master_order_beli`.`order_biaya` AS `order_biaya`,`master_order_beli`.`order_bayar` AS `order_bayar`,`master_order_beli`.`order_keterangan` AS `order_keterangan`,`detail_order_beli`.`dorder_master` AS `dorder_master`,`detail_order_beli`.`dorder_produk` AS `dorder_produk`,`detail_order_beli`.`dorder_satuan` AS `dorder_satuan`,`detail_order_beli`.`dorder_jumlah` AS `dorder_jumlah`,`detail_order_beli`.`dorder_harga` AS `dorder_harga`,`detail_order_beli`.`dorder_diskon` AS `dorder_diskon`,`satuan`.`satuan_id` AS `satuan_id`,`satuan`.`satuan_kode` AS `satuan_kode`,`satuan`.`satuan_nama` AS `satuan_nama`,`vu_produk`.`produk_kode` AS `produk_kode`,`vu_produk`.`produk_group` AS `produk_group`,`vu_produk`.`produk_kategori` AS `produk_kategori`,`vu_produk`.`produk_kontribusi` AS `produk_kontribusi`,`vu_produk`.`produk_nama` AS `produk_nama`,`vu_produk`.`produk_satuan` AS `produk_satuan`,`vu_produk`.`produk_volume` AS `produk_volume`,`vu_produk`.`produk_jenis` AS `produk_jenis`,`vu_produk`.`produk_kodelama` AS `produk_kodelama`,`vu_produk`.`group_nama` AS `group_nama`,`vu_produk`.`kategori_nama` AS `kategori_nama`,`vu_produk`.`kategori_jenis` AS `kategori_jenis`,`vu_produk`.`jenis_nama` AS `jenis_nama`,`vu_produk`.`jenis_kelompok` AS `jenis_kelompok`,`vu_produk`.`kategori2_nama` AS `kategori2_nama`,((`detail_order_beli`.`dorder_jumlah` * `detail_order_beli`.`dorder_diskon`) * `detail_order_beli`.`dorder_harga`) AS `diskon_nilai`,((`detail_order_beli`.`dorder_jumlah` * `detail_order_beli`.`dorder_harga`) * (100 - `detail_order_beli`.`dorder_diskon`)) AS `subtotal` from ((((`detail_order_beli` join `master_order_beli` on((`detail_order_beli`.`dorder_master` = `master_order_beli`.`order_id`))) join `supplier` on((`master_order_beli`.`order_supplier` = `supplier`.`supplier_id`))) join `satuan` on((`detail_order_beli`.`dorder_produk` = `satuan`.`satuan_id`))) join `vu_produk` on((`detail_order_beli`.`dorder_produk` = `vu_produk`.`produk_id`)));

-- ----------------------------
-- View structure for vu_detail_retur_jual_produk
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_detail_retur_jual_produk` AS select `detail_retur_jual_produk`.`drproduk_id` AS `drproduk_id`,`detail_retur_jual_produk`.`drproduk_master` AS `drproduk_master`,`detail_retur_jual_produk`.`drproduk_produk` AS `drproduk_produk`,`detail_retur_jual_produk`.`drproduk_satuan` AS `drproduk_satuan`,`detail_retur_jual_produk`.`drproduk_jumlah` AS `drproduk_jumlah`,`detail_retur_jual_produk`.`drproduk_harga` AS `drproduk_harga` from (`master_retur_jual_produk` join `detail_retur_jual_produk` on((`detail_retur_jual_produk`.`drproduk_master` = `master_retur_jual_produk`.`rproduk_id`)));

-- ----------------------------
-- View structure for vu_total_jual_paket_group
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_total_jual_paket_group` AS select ifnull(sum(`detail_jual_paket`.`dpaket_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`detail_jual_paket`.`dpaket_harga` * `detail_jual_paket`.`dpaket_jumlah`) * (100 - `detail_jual_paket`.`dpaket_diskon`)) / 100)),0) AS `total_nilai`,`detail_jual_paket`.`dpaket_master` AS `dpaket_master` from `detail_jual_paket` group by `detail_jual_paket`.`dpaket_master`;

-- ----------------------------
-- View structure for vu_total_jual_produk_group
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_total_jual_produk_group` AS select ifnull(sum(`detail_jual_produk`.`dproduk_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`detail_jual_produk`.`dproduk_harga` * `detail_jual_produk`.`dproduk_jumlah`) * (100 - `detail_jual_produk`.`dproduk_diskon`)) / 100)),0) AS `total_nilai`,`detail_jual_produk`.`dproduk_master` AS `dproduk_master` from `detail_jual_produk` group by `detail_jual_produk`.`dproduk_master`;

-- ----------------------------
-- View structure for vu_total_jual_rawat_group
-- ----------------------------
CREATE  OR REPLACE VIEW `vu_total_jual_rawat_group` AS select ifnull(sum(`detail_jual_rawat`.`drawat_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) * (100 - `detail_jual_rawat`.`drawat_diskon`)) / 100)),0) AS `total_nilai`,`detail_jual_rawat`.`drawat_master` AS `drawat_master` from `detail_jual_rawat` group by `detail_jual_rawat`.`drawat_master`;

-- ----------------------------
-- View structure for vu_total_order_group
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_total_order_group` AS select sum(`detail_order_beli`.`dorder_jumlah`) AS `jumlah_barang`,sum((((`detail_order_beli`.`dorder_harga` * `detail_order_beli`.`dorder_jumlah`) * (100 - `detail_order_beli`.`dorder_diskon`)) / 100)) AS `total_nilai`,`detail_order_beli`.`dorder_master` AS `dorder_master` from `detail_order_beli` group by `detail_order_beli`.`dorder_master`;

-- ----------------------------
-- View structure for vu_total_retur_group
-- ----------------------------
CREATE  OR REPLACE  VIEW `vu_total_retur_group` AS select `detail_retur_beli`.`drbeli_master` AS `drbeli_master`,sum(`detail_retur_beli`.`drbeli_jumlah`) AS `jumlah_barang`,sum((`detail_retur_beli`.`drbeli_harga` * `detail_retur_beli`.`drbeli_jumlah`)) AS `total_nilai` from `detail_retur_beli` group by `detail_retur_beli`.`drbeli_master`;

-- ----------------------------
-- View structure for vu_total_retur_jual_produk_group
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_total_retur_jual_produk_group` AS select ifnull(sum(`detail_retur_jual_produk`.`drproduk_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`detail_retur_jual_produk`.`drproduk_harga` * `detail_retur_jual_produk`.`drproduk_jumlah`) * (100 - `detail_retur_jual_produk`.`drproduk_diskon`)) / 100)),0) AS `total_nilai`,`detail_retur_jual_produk`.`drproduk_master` AS `drproduk_master` from `detail_retur_jual_produk` group by `detail_retur_jual_produk`.`drproduk_master`;

-- ----------------------------
-- View structure for vu_trans_order
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_trans_order` AS select `master_order_beli`.`order_no` AS `order_no`,`master_order_beli`.`order_supplier` AS `order_supplier`,`master_order_beli`.`order_tanggal` AS `order_tanggal`,`master_order_beli`.`order_carabayar` AS `order_carabayar`,`master_order_beli`.`order_diskon` AS `order_diskon`,`master_order_beli`.`order_biaya` AS `order_biaya`,`master_order_beli`.`order_bayar` AS `order_bayar`,`master_order_beli`.`order_keterangan` AS `order_keterangan`,`vu_total_order_group`.`jumlah_barang` AS `jumlah_barang`,`vu_total_order_group`.`total_nilai` AS `total_nilai`,`supplier`.`supplier_kategori` AS `supplier_kategori`,`supplier`.`supplier_nama` AS `supplier_nama`,`supplier`.`supplier_alamat` AS `supplier_alamat`,`supplier`.`supplier_kota` AS `supplier_kota`,`supplier`.`supplier_kodepos` AS `supplier_kodepos`,`supplier`.`supplier_propinsi` AS `supplier_propinsi`,`supplier`.`supplier_negara` AS `supplier_negara`,`supplier`.`supplier_notelp` AS `supplier_notelp`,`supplier`.`supplier_notelp2` AS `supplier_notelp2`,`supplier`.`supplier_nofax` AS `supplier_nofax`,`supplier`.`supplier_email` AS `supplier_email`,`supplier`.`supplier_website` AS `supplier_website`,`supplier`.`supplier_cp` AS `supplier_cp`,`supplier`.`supplier_contact_cp` AS `supplier_contact_cp`,`supplier`.`supplier_akun` AS `supplier_akun`,`supplier`.`supplier_keterangan` AS `supplier_keterangan` from ((`vu_total_order_group` join `master_order_beli` on((`vu_total_order_group`.`dorder_master` = `master_order_beli`.`order_id`))) join `supplier` on((`master_order_beli`.`order_supplier` = `supplier`.`supplier_id`)));

-- ----------------------------
-- View structure for vu_trans_paket
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_trans_paket` AS select `master_jual_paket`.`jpaket_nobukti` AS `no_bukti`,`master_jual_paket`.`jpaket_cust` AS `cust_id`,`master_jual_paket`.`jpaket_tanggal` AS `tanggal`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota`,ifnull(`vu_total_jual_paket_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_paket_group`.`total_nilai`,0) AS `total_nilai`,ifnull(`master_jual_paket`.`jpaket_diskon`,0) AS `diskon`,ifnull(`master_jual_paket`.`jpaket_cashback`,0) AS `cashback`,ifnull(`jual_kredit`.`jkredit_nilai`,0) AS `kredit`,ifnull(`jual_cek`.`jcek_nilai`,0) AS `cek`,ifnull(`jual_card`.`jcard_nilai`,0) AS `card`,ifnull(`jual_kwitansi`.`jkwitansi_nilai`,0) AS `kuintansi`,ifnull(`jual_transfer`.`jtransfer_nilai`,0) AS `transfer`,ifnull(`jual_tunai`.`jtunai_nilai`,0) AS `tunai` from ((((((((`master_jual_paket` left join `vu_total_jual_paket_group` on((`vu_total_jual_paket_group`.`dpaket_master` = `master_jual_paket`.`jpaket_id`))) left join `vu_customer` on((`master_jual_paket`.`jpaket_cust` = `vu_customer`.`cust_id`))) left join `jual_card` on((`jual_card`.`jcard_ref` = `master_jual_paket`.`jpaket_nobukti`))) left join `jual_cek` on((`jual_cek`.`jcek_ref` = `master_jual_paket`.`jpaket_nobukti`))) left join `jual_kredit` on((`jual_kredit`.`jkredit_ref` = `master_jual_paket`.`jpaket_nobukti`))) left join `jual_kwitansi` on((`jual_kwitansi`.`jkwitansi_ref` = `master_jual_paket`.`jpaket_nobukti`))) left join `jual_transfer` on((`jual_transfer`.`jtransfer_ref` = `master_jual_paket`.`jpaket_nobukti`))) left join `jual_tunai` on((`jual_tunai`.`jtunai_ref` = `master_jual_paket`.`jpaket_nobukti`)));

-- ----------------------------
-- View structure for vu_trans_produk
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_trans_produk` AS select `master_jual_produk`.`jproduk_nobukti` AS `no_bukti`,`master_jual_produk`.`jproduk_cust` AS `cust_id`,`master_jual_produk`.`jproduk_tanggal` AS `tanggal`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota`,ifnull(`vu_total_jual_produk_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_produk_group`.`total_nilai`,0) AS `total_nilai`,ifnull(`master_jual_produk`.`jproduk_diskon`,0) AS `diskon`,ifnull(`master_jual_produk`.`jproduk_cashback`,0) AS `cashback`,ifnull(`jual_kredit`.`jkredit_nilai`,0) AS `kredit`,ifnull(`jual_cek`.`jcek_nilai`,0) AS `cek`,ifnull(`jual_card`.`jcard_nilai`,0) AS `card`,ifnull(`jual_kwitansi`.`jkwitansi_nilai`,0) AS `kuintansi`,ifnull(`jual_transfer`.`jtransfer_nilai`,0) AS `transfer`,ifnull(`jual_tunai`.`jtunai_nilai`,0) AS `tunai` from ((((((((`master_jual_produk` left join `vu_total_jual_produk_group` on((`vu_total_jual_produk_group`.`dproduk_master` = `master_jual_produk`.`jproduk_id`))) left join `vu_customer` on((`master_jual_produk`.`jproduk_cust` = `vu_customer`.`cust_id`))) left join `jual_card` on((`jual_card`.`jcard_ref` = `master_jual_produk`.`jproduk_nobukti`))) left join `jual_cek` on((`jual_cek`.`jcek_ref` = `master_jual_produk`.`jproduk_nobukti`))) left join `jual_kredit` on((`jual_kredit`.`jkredit_ref` = `master_jual_produk`.`jproduk_nobukti`))) left join `jual_kwitansi` on((`jual_kwitansi`.`jkwitansi_ref` = `master_jual_produk`.`jproduk_nobukti`))) left join `jual_transfer` on((`jual_transfer`.`jtransfer_ref` = `master_jual_produk`.`jproduk_nobukti`))) left join `jual_tunai` on((`jual_tunai`.`jtunai_ref` = `master_jual_produk`.`jproduk_nobukti`)));

-- ----------------------------
-- View structure for vu_trans_rawat
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_trans_rawat` AS select `master_jual_rawat`.`jrawat_nobukti` AS `no_bukti`,`master_jual_rawat`.`jrawat_cust` AS `cust_id`,`master_jual_rawat`.`jrawat_tanggal` AS `tanggal`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota`,ifnull(`vu_total_jual_rawat_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_rawat_group`.`total_nilai`,0) AS `total_nilai`,ifnull(`master_jual_rawat`.`jrawat_diskon`,0) AS `diskon`,ifnull(`master_jual_rawat`.`jrawat_cashback`,0) AS `cashback`,ifnull(`jual_kredit`.`jkredit_nilai`,0) AS `kredit`,ifnull(`jual_cek`.`jcek_nilai`,0) AS `cek`,ifnull(`jual_card`.`jcard_nilai`,0) AS `card`,ifnull(`jual_kwitansi`.`jkwitansi_nilai`,0) AS `kuintansi`,ifnull(`jual_transfer`.`jtransfer_nilai`,0) AS `transfer`,ifnull(`jual_tunai`.`jtunai_nilai`,0) AS `tunai` from ((((((((`master_jual_rawat` left join `vu_total_jual_rawat_group` on((`vu_total_jual_rawat_group`.`drawat_master` = `master_jual_rawat`.`jrawat_id`))) left join `vu_customer` on((`master_jual_rawat`.`jrawat_cust` = `vu_customer`.`cust_id`))) left join `jual_card` on((`jual_card`.`jcard_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_cek` on((`jual_cek`.`jcek_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_kredit` on((`jual_kredit`.`jkredit_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_kwitansi` on((`jual_kwitansi`.`jkwitansi_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_transfer` on((`jual_transfer`.`jtransfer_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_tunai` on((`jual_tunai`.`jtunai_ref` = `master_jual_rawat`.`jrawat_nobukti`)));

-- ----------------------------
-- View structure for vu_trans_retur_produk
-- ----------------------------
CREATE  OR REPLACE   VIEW `vu_trans_retur_produk` AS select `master_retur_jual_produk`.`rproduk_nobukti` AS `no_bukti`,`master_retur_jual_produk`.`rproduk_cust` AS `cust_id`,`master_retur_jual_produk`.`rproduk_tanggal` AS `tanggal`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota`,`master_jual_produk`.`jproduk_nobukti` AS `no_bukti_jual`,`master_jual_produk`.`jproduk_tanggal` AS `tanggal_jual`,ifnull(`vu_total_retur_jual_produk_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_retur_jual_produk_group`.`total_nilai`,0) AS `total_nilai`,ifnull(`master_retur_jual_produk`.`rproduk_diskon`,0) AS `diskon`,ifnull(`master_retur_jual_produk`.`rproduk_cashback`,0) AS `cashback` from (((`master_retur_jual_produk` left join `vu_total_retur_jual_produk_group` on((`vu_total_retur_jual_produk_group`.`drproduk_master` = `master_retur_jual_produk`.`rproduk_id`))) left join `vu_customer` on((`master_retur_jual_produk`.`rproduk_cust` = `vu_customer`.`cust_id`))) left join `master_jual_produk` on((`master_retur_jual_produk`.`rproduk_nobuktijual` = `master_jual_produk`.`jproduk_id`)));
