-- Penambahan Voucher, dari semula di Cara Bayar, kini dipindah ke Diskon Tambahan (Rp). Untuk sementara, Cara Bayar Voucher dihidden dulu.


ALTER TABLE `master_jual_produk` ADD `jproduk_ket_disk` VARCHAR( 250 ) NOT NULL;
ALTER TABLE `master_jual_rawat` ADD `jrawat_ket_disk` VARCHAR( 250 ) NOT NULL;
ALTER TABLE `master_jual_paket` ADD `jpaket_ket_disk` VARCHAR( 250 ) NOT NULL;

CREATE OR REPLACE VIEW `vu_jproduk` AS select `master_jual_produk`.`jproduk_id` AS `jproduk_id`,`master_jual_produk`.`jproduk_nobukti` AS `jproduk_nobukti`,`master_jual_produk`.`jproduk_stat_dok` AS `jproduk_stat_dok`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`member_no` AS `member_no`,`vu_customer`.`member_valid` AS `member_valid`,`master_jual_produk`.`jproduk_cust` AS `jproduk_cust`,`master_jual_produk`.`jproduk_tanggal` AS `jproduk_tanggal`,`master_jual_produk`.`jproduk_diskon` AS `jproduk_diskon`,`master_jual_produk`.`jproduk_cashback` AS `jproduk_cashback`,`master_jual_produk`.`jproduk_cara` AS `jproduk_cara`,`master_jual_produk`.`jproduk_cara2` AS `jproduk_cara2`,`master_jual_produk`.`jproduk_cara3` AS `jproduk_cara3`,`master_jual_produk`.`jproduk_bayar` AS `jproduk_bayar`,`master_jual_produk`.`jproduk_totalbiaya` AS `jproduk_totalbiaya`,`master_jual_produk`.`jproduk_keterangan` AS `jproduk_keterangan`,`master_jual_produk`.`jproduk_creator` AS `jproduk_creator`,`master_jual_produk`.`jproduk_ket_disk` AS `jproduk_ket_disk`,`master_jual_produk`.`jproduk_date_create` AS `jproduk_date_create`,`master_jual_produk`.`jproduk_update` AS `jproduk_update`,`master_jual_produk`.`jproduk_date_update` AS `jproduk_date_update`,`master_jual_produk`.`jproduk_revised` AS `jproduk_revised` from (`master_jual_produk` left join `vu_customer` on((`master_jual_produk`.`jproduk_cust` = `vu_customer`.`cust_id`)));

CREATE OR REPLACE VIEW `vu_jrawat_pr` AS select `master_jual_rawat`.`jrawat_id` AS `jrawat_id`,`master_jual_rawat`.`jrawat_nobukti` AS `jrawat_nobukti`,0 AS `dpaket_id`,`master_jual_rawat`.`jrawat_stat_dok` AS `jrawat_stat_dok`,`vu_customer`.`cust_nama` AS `cust_nama`,`master_jual_rawat`.`jrawat_cust` AS `jrawat_cust`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`member_no` AS `member_no`,`vu_customer`.`member_valid` AS `member_valid`,`master_jual_rawat`.`jrawat_tanggal` AS `jrawat_tanggal`,`master_jual_rawat`.`jrawat_diskon` AS `jrawat_diskon`,`master_jual_rawat`.`jrawat_cashback` AS `jrawat_cashback`,`master_jual_rawat`.`jrawat_cara` AS `jrawat_cara`,`master_jual_rawat`.`jrawat_cara2` AS `jrawat_cara2`,`master_jual_rawat`.`jrawat_cara3` AS `jrawat_cara3`,`master_jual_rawat`.`jrawat_totalbiaya` AS `jrawat_totalbiaya`,`master_jual_rawat`.`jrawat_bayar` AS `jrawat_bayar`,`master_jual_rawat`.`jrawat_keterangan` AS `jrawat_keterangan`,`master_jual_rawat`.`jrawat_ket_disk` AS `jrawat_ket_disk`,`master_jual_rawat`.`jrawat_creator` AS `jrawat_creator`,`master_jual_rawat`.`jrawat_date_create` AS `jrawat_date_create`,`master_jual_rawat`.`jrawat_update` AS `jrawat_update`,`master_jual_rawat`.`jrawat_date_update` AS `jrawat_date_update`,`master_jual_rawat`.`jrawat_revised` AS `jrawat_revised`,if((substr(`master_jual_rawat`.`jrawat_nobukti`,1,2) = _latin1'PK'),_utf8'paket',_utf8'') AS `keterangan_paket` from (`master_jual_rawat` left join `vu_customer` on((`master_jual_rawat`.`jrawat_cust` = `vu_customer`.`cust_id`)));

CREATE OR REPLACE VIEW `vu_jpaket` AS select `master_jual_paket`.`jpaket_id` AS `jpaket_id`,`master_jual_paket`.`jpaket_nobukti` AS `jpaket_nobukti`,`master_jual_paket`.`jpaket_stat_dok` AS `jpaket_stat_dok`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`member_no` AS `member_no`,`vu_customer`.`member_valid` AS `member_valid`,`master_jual_paket`.`jpaket_cust` AS `jpaket_cust`,`master_jual_paket`.`jpaket_tanggal` AS `jpaket_tanggal`,`master_jual_paket`.`jpaket_diskon` AS `jpaket_diskon`,`master_jual_paket`.`jpaket_cashback` AS `jpaket_cashback`,`master_jual_paket`.`jpaket_cara` AS `jpaket_cara`,`master_jual_paket`.`jpaket_cara2` AS `jpaket_cara2`,`master_jual_paket`.`jpaket_cara3` AS `jpaket_cara3`,`master_jual_paket`.`jpaket_bayar` AS `jpaket_bayar`,`master_jual_paket`.`jpaket_totalbiaya` AS `jpaket_totalbiaya`,`master_jual_paket`.`jpaket_keterangan` AS `jpaket_keterangan`,`master_jual_paket`.`jpaket_ket_disk` AS `jpaket_ket_disk`,`master_jual_paket`.`jpaket_creator` AS `jpaket_creator`,`master_jual_paket`.`jpaket_date_create` AS `jpaket_date_create`,`master_jual_paket`.`jpaket_update` AS `jpaket_update`,`master_jual_paket`.`jpaket_date_update` AS `jpaket_date_update`,`master_jual_paket`.`jpaket_revised` AS `jpaket_revised` from (`master_jual_paket` left join `vu_customer` on((`master_jual_paket`.`jpaket_cust` = `vu_customer`.`cust_id`)));