CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jproduk_total_point` AS select `master_jual_produk`.`jproduk_id` AS `jproduk_id`,`master_jual_produk`.`jproduk_nobukti` AS `jproduk_nobukti`,`master_jual_produk`.`jproduk_tanggal` AS `jproduk_tanggal`,`master_jual_produk`.`jproduk_cust` AS `jproduk_cust`,((sum((((`detail_jual_produk`.`dproduk_jumlah` * `detail_jual_produk`.`dproduk_harga`) * `produk`.`produk_point`) * ((100 - `detail_jual_produk`.`dproduk_diskon`) / 100))) * ((100 - `master_jual_produk`.`jproduk_diskon`) / 100)) - `master_jual_produk`.`jproduk_cashback`) AS `dproduk_total_nilai`,floor((((sum((((`detail_jual_produk`.`dproduk_jumlah` * `detail_jual_produk`.`dproduk_harga`) * `produk`.`produk_point`) * ((100 - `detail_jual_produk`.`dproduk_diskon`) / 100))) * ((100 - `master_jual_produk`.`jproduk_diskon`) / 100)) - `master_jual_produk`.`jproduk_cashback`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1))) AS `jproduk_total_point` from ((`detail_jual_produk` join `master_jual_produk` on((`detail_jual_produk`.`dproduk_master` = `master_jual_produk`.`jproduk_id`))) join `produk` on((`detail_jual_produk`.`dproduk_produk` = `produk`.`produk_id`))) where ((`produk`.`produk_point` > 0) and `master_jual_produk`.`jproduk_cust`) group by `detail_jual_produk`.`dproduk_master`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jproduk_totalbiaya` AS select `detail_jual_produk`.`dproduk_master` AS `dproduk_master`,((sum(((`detail_jual_produk`.`dproduk_jumlah` * `detail_jual_produk`.`dproduk_harga`) * ((100 - `detail_jual_produk`.`dproduk_diskon`) / 100))) * ((100 - `master_jual_produk`.`jproduk_diskon`) / 100)) - `master_jual_produk`.`jproduk_cashback`) AS `jproduk_totalbiaya` from (`detail_jual_produk` left join `master_jual_produk` on((`detail_jual_produk`.`dproduk_master` = `master_jual_produk`.`jproduk_id`))) group by `detail_jual_produk`.`dproduk_master`;




CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jpaket_total_point` AS select `master_jual_paket`.`jpaket_id` AS `jpaket_id`,`master_jual_paket`.`jpaket_nobukti` AS `jpaket_nobukti`,`master_jual_paket`.`jpaket_tanggal` AS `jpaket_tanggal`,`master_jual_paket`.`jpaket_cust` AS `jpaket_cust`,((sum((((`detail_jual_paket`.`dpaket_jumlah` * `detail_jual_paket`.`dpaket_harga`) * `paket`.`paket_point`) * ((100 - `detail_jual_paket`.`dpaket_diskon`) / 100))) * ((100 - `master_jual_paket`.`jpaket_diskon`) / 100)) - `master_jual_paket`.`jpaket_cashback`) AS `dpaket_total_nilai`,floor((((sum((((`detail_jual_paket`.`dpaket_jumlah` * `detail_jual_paket`.`dpaket_harga`) * `paket`.`paket_point`) * ((100 - `detail_jual_paket`.`dpaket_diskon`) / 100))) * ((100 - `master_jual_paket`.`jpaket_diskon`) / 100)) - `master_jual_paket`.`jpaket_cashback`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1))) AS `jpaket_total_point` from ((`detail_jual_paket` join `master_jual_paket` on((`detail_jual_paket`.`dpaket_master` = `master_jual_paket`.`jpaket_id`))) join `paket` on((`detail_jual_paket`.`dpaket_paket` = `paket`.`paket_id`))) where ((`paket`.`paket_point` > 0) and `master_jual_paket`.`jpaket_cust`) group by `detail_jual_paket`.`dpaket_master`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jpaket_totalbiaya` AS select `detail_jual_paket`.`dpaket_master` AS `dpaket_master`,((sum(((`detail_jual_paket`.`dpaket_jumlah` * `detail_jual_paket`.`dpaket_harga`) * ((100 - `detail_jual_paket`.`dpaket_diskon`) / 100))) * ((100 - `master_jual_paket`.`jpaket_diskon`) / 100)) - `master_jual_paket`.`jpaket_cashback`) AS `jpaket_totalbiaya` from (`detail_jual_paket` left join `master_jual_paket` on((`detail_jual_paket`.`dpaket_master` = `master_jual_paket`.`jpaket_id`))) group by `detail_jual_paket`.`dpaket_master`;




CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jrawat_total_point` AS select `master_jual_rawat`.`jrawat_id` AS `jrawat_id`,`master_jual_rawat`.`jrawat_nobukti` AS `jrawat_nobukti`,`master_jual_rawat`.`jrawat_tanggal` AS `jrawat_tanggal`,`master_jual_rawat`.`jrawat_cust` AS `jrawat_cust`,((sum((((`detail_jual_rawat`.`drawat_jumlah` * `detail_jual_rawat`.`drawat_harga`) * `perawatan`.`rawat_point`) * ((100 - `detail_jual_rawat`.`drawat_diskon`) / 100))) * ((100 - `master_jual_rawat`.`jrawat_diskon`) / 100)) - `master_jual_rawat`.`jrawat_cashback`) AS `drawat_total_nilai`,floor((((sum((((`detail_jual_rawat`.`drawat_jumlah` * `detail_jual_rawat`.`drawat_harga`) * `perawatan`.`rawat_point`) * ((100 - `detail_jual_rawat`.`drawat_diskon`) / 100))) * ((100 - `master_jual_rawat`.`jrawat_diskon`) / 100)) - `master_jual_rawat`.`jrawat_cashback`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1))) AS `jrawat_total_point` from ((`detail_jual_rawat` join `master_jual_rawat` on((`detail_jual_rawat`.`drawat_master` = `master_jual_rawat`.`jrawat_id`))) join `perawatan` on((`detail_jual_rawat`.`drawat_rawat` = `perawatan`.`rawat_id`))) where ((`perawatan`.`rawat_point` > 0) and `master_jual_rawat`.`jrawat_cust`) group by `detail_jual_rawat`.`drawat_master`;