DROP TABLE crm_setup;

CREATE TABLE IF NOT EXISTS `crm_setup` (
  `setcrm_id` int(11) NOT NULL AUTO_INCREMENT,
  `setcrm_frequency_count` float DEFAULT NULL,
  `setcrm_frequency_days` float DEFAULT NULL,
  `setcrm_frequency_value_morethan` float DEFAULT NULL,
  `setcrm_frequency_value_equal` float DEFAULT NULL,
  `setcrm_frequency_value_lessthan` float DEFAULT NULL,
  `setcrm_recency_days` float DEFAULT NULL,
  `setcrm_recency_value_morethan` float DEFAULT NULL,
  `setcrm_recency_value_lessthan` float DEFAULT NULL,
  `setcrm_spending_days` float NOT NULL,
  `setcrm_spending_value_morethan` float DEFAULT NULL,
  `setcrm_spending_value_equal` float DEFAULT NULL,
  `setcrm_spending_value_lessthan` float DEFAULT NULL,
  `setcrm_highmargin_treatment` float DEFAULT NULL,
  `setcrm_highmargin_days` float DEFAULT NULL,
  `setcrm_highmargin_value_morethan` float DEFAULT NULL,
  `setcrm_highmargin_value_equal` float DEFAULT NULL,
  `setcrm_highmargin_value_lessthan` float DEFAULT NULL,
  `setcrm_referal_person` float DEFAULT NULL,
  `setcrm_referal_days` float DEFAULT NULL,
  `setcrm_referal_morethan` float DEFAULT NULL,
  `setcrm_referal_equal` float DEFAULT NULL,
  `setcrm_referal_lessthan` float DEFAULT NULL,
  `setcrm_kerewelan_high` float DEFAULT NULL,
  `setcrm_kerewelan_normal` float DEFAULT NULL,
  `setcrm_kerewelan_low` float DEFAULT NULL,
  `setcrm_disiplin_days` float NOT NULL,
  `setcrm_disiplin_persentase_pembatalan` float NOT NULL,
  `setcrm_disiplin_persentase_telat` float NOT NULL,
  `setcrm_disiplin_menit_telat` float NOT NULL,
  `setcrm_disiplin_batal_value_morethan` float NOT NULL,
  `setcrm_disiplin_batal_value_lessthan` float NOT NULL,
  `setcrm_disiplin_telat_value_morethan` float NOT NULL,
  `setcrm_disiplin_telat_value_lessthan` float NOT NULL,
  `setcrm_treatment_days` float DEFAULT NULL,
  `setcrm_treatment_nonmedis` float DEFAULT NULL,
  `setcrm_treatment_medis` float DEFAULT NULL,
  `setcrm_treatment_morethan` float DEFAULT NULL,
  `setcrm_treatment_equal` float DEFAULT NULL,
  `setcrm_treatment_lessthan` float DEFAULT NULL,
  `setcrm_result_nilai_atas` float NOT NULL,
  `setcrm_result_nilai_bawah` float NOT NULL,
  `setcrm_author` varchar(50) DEFAULT NULL,
  `setcrm_date_create` datetime NOT NULL,
  `setcrm_update` varchar(50) NOT NULL,
  `setcrm_date_update` datetime NOT NULL,
  `setcrm_revised` int(11) NOT NULL,
  PRIMARY KEY (`setcrm_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE crm_value;

CREATE TABLE IF NOT EXISTS `crm_value` (
  `crmvalue_id` int(10) NOT NULL AUTO_INCREMENT,
  `crmvalue_date` datetime DEFAULT NULL,
  `crmvalue_cust` int(10) DEFAULT '0',
  `crmvalue_frequency` float DEFAULT '0',
  `crmvalue_frequency_real` int(10) DEFAULT NULL,
  `crmvalue_recency` float DEFAULT '0',
  `crmvalue_recency_real` int(10) DEFAULT NULL,
  `crmvalue_spending` double DEFAULT '0',
  `crmvalue_spending_real_rp` double DEFAULT '0',
  `crmvalue_spending_real_kunj` int(11) DEFAULT '0',
  `crmvalue_highmargin` double DEFAULT '0',
  `crmvalue_highmargin_real` double DEFAULT '0',
  `crmvalue_referal` float DEFAULT '0',
  `crmvalue_referal_real` int(10) DEFAULT NULL,
  `crmvalue_kerewelan` float DEFAULT '0',
  `crmvalue_kerewelan_real` varchar(10) DEFAULT NULL,
  `crmvalue_disiplin_batal` decimal(3,1) DEFAULT '0.0',
  `crmvalue_disiplin_batal_real` decimal(2,2) DEFAULT NULL,
  `crmvalue_disiplin_telat` decimal(3,1) DEFAULT NULL,
  `crmvalue_disiplin_telat_real` decimal(2,2) DEFAULT NULL,
  `crmvalue_treatment` float DEFAULT '0',
  `crmvalue_treatment_non_medis_real` int(10) DEFAULT NULL,
  `crmvalue_treatment_medis_real` int(10) DEFAULT NULL,
  `crmvalue_total` decimal(3,1) DEFAULT NULL,
  `crmvalue_priority` varchar(10) DEFAULT NULL,
  `crmvalue_author` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`crmvalue_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;