CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jrawat_trans` AS select `master_jual_rawat`.`jrawat_id` AS `jrawat_id`,`master_jual_rawat`.`jrawat_nobukti` AS `jrawat_nobukti`,`master_jual_rawat`.`jrawat_cust` AS `jrawat_cust`,`master_jual_rawat`.`jrawat_tanggal` AS `jrawat_tanggal`,floor(sum(((((`detail_jual_rawat`.`drawat_jumlah` * `detail_jual_rawat`.`drawat_harga`) * ((100 - `detail_jual_rawat`.`drawat_diskon`) / 100)) * `perawatan`.`rawat_point`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1)))) AS `jrawat_total_point` from ((`detail_jual_rawat` join `master_jual_rawat` on(((`detail_jual_rawat`.`drawat_master` = `master_jual_rawat`.`jrawat_id`) and (`master_jual_rawat`.`jrawat_stat_dok` = 'Tertutup')))) join `perawatan` on((`detail_jual_rawat`.`drawat_rawat` = `perawatan`.`rawat_id`))) group by `detail_jual_rawat`.`drawat_master`;


CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jrawat_total_point` AS select `vu_jrawat_trans`.`jrawat_id` AS `jrawat_id`,`vu_jrawat_trans`.`jrawat_nobukti` AS `jrawat_nobukti`,`vu_jrawat_trans`.`jrawat_cust` AS `jrawat_cust`,`vu_jrawat_trans`.`jrawat_tanggal` AS `jrawat_tanggal`,`vu_jrawat_trans`.`jrawat_total_point` AS `jrawat_total_point` from (`vu_jrawat_trans` join `member` on(((`vu_jrawat_trans`.`jrawat_cust` = `member`.`member_cust`) and ((`member`.`member_valid` + interval (select `member_setup`.`setmember_periodetenggang` AS `setmember_periodetenggang` from `member_setup` limit 1) day) >= `vu_jrawat_trans`.`jrawat_tanggal`) and (`member`.`member_register` < `vu_jrawat_trans`.`jrawat_tanggal`))));


CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jproduk_trans` AS select `master_jual_produk`.`jproduk_id` AS `jproduk_id`,`master_jual_produk`.`jproduk_nobukti` AS `jproduk_nobukti`,`master_jual_produk`.`jproduk_cust` AS `jproduk_cust`,`master_jual_produk`.`jproduk_tanggal` AS `jproduk_tanggal`,floor(sum(((((`detail_jual_produk`.`dproduk_jumlah` * `detail_jual_produk`.`dproduk_harga`) * ((100 - `detail_jual_produk`.`dproduk_diskon`) / 100)) * `produk`.`produk_point`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1)))) AS `jproduk_total_point` from ((`detail_jual_produk` join `master_jual_produk` on(((`detail_jual_produk`.`dproduk_master` = `master_jual_produk`.`jproduk_id`) and (`master_jual_produk`.`jproduk_stat_dok` = 'Tertutup')))) join `produk` on((`detail_jual_produk`.`dproduk_produk` = `produk`.`produk_id`))) group by `detail_jual_produk`.`dproduk_master`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jproduk_total_point` AS select `vu_jproduk_trans`.`jproduk_id` AS `jproduk_id`,`vu_jproduk_trans`.`jproduk_nobukti` AS `jproduk_nobukti`,`vu_jproduk_trans`.`jproduk_cust` AS `jproduk_cust`,`vu_jproduk_trans`.`jproduk_tanggal` AS `jproduk_tanggal`,`vu_jproduk_trans`.`jproduk_total_point` AS `jproduk_total_point` from (`vu_jproduk_trans` join `member` on(((`vu_jproduk_trans`.`jproduk_cust` = `member`.`member_cust`) and ((`member`.`member_valid` + interval (select `member_setup`.`setmember_periodetenggang` AS `setmember_periodetenggang` from `member_setup` limit 1) day) >= `vu_jproduk_trans`.`jproduk_tanggal`) and (`member`.`member_register` < `vu_jproduk_trans`.`jproduk_tanggal`))));


CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jpaket_trans` AS select `master_jual_paket`.`jpaket_id` AS `jpaket_id`,`master_jual_paket`.`jpaket_nobukti` AS `jpaket_nobukti`,`master_jual_paket`.`jpaket_cust` AS `jpaket_cust`,`master_jual_paket`.`jpaket_tanggal` AS `jpaket_tanggal`,floor(sum(((((`detail_jual_paket`.`dpaket_jumlah` * `detail_jual_paket`.`dpaket_harga`) * ((100 - `detail_jual_paket`.`dpaket_diskon`) / 100)) * `paket`.`paket_point`) / (select `member_setup`.`setmember_point_perrp` AS `setmember_point_perrp` from `member_setup` limit 1)))) AS `jpaket_total_point` from ((`detail_jual_paket` join `master_jual_paket` on(((`detail_jual_paket`.`dpaket_master` = `master_jual_paket`.`jpaket_id`) and (`master_jual_paket`.`jpaket_stat_dok` = 'Tertutup')))) join `paket` on((`detail_jual_paket`.`dpaket_paket` = `paket`.`paket_id`))) group by `detail_jual_paket`.`dpaket_master`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `vu_jpaket_total_point` AS select `vu_jpaket_trans`.`jpaket_id` AS `jpaket_id`,`vu_jpaket_trans`.`jpaket_nobukti` AS `jpaket_nobukti`,`vu_jpaket_trans`.`jpaket_cust` AS `jpaket_cust`,`vu_jpaket_trans`.`jpaket_tanggal` AS `jpaket_tanggal`,`vu_jpaket_trans`.`jpaket_total_point` AS `jpaket_total_point` from (`vu_jpaket_trans` join `member` on(((`vu_jpaket_trans`.`jpaket_cust` = `member`.`member_cust`) and ((`member`.`member_valid` + interval (select `member_setup`.`setmember_periodetenggang` AS `setmember_periodetenggang` from `member_setup` limit 1) day) >= `vu_jpaket_trans`.`jpaket_tanggal`) and (`member`.`member_register` < `vu_jpaket_trans`.`jpaket_tanggal`))));