
CREATE OR REPLACE VIEW `vu_sum_jual_card` AS select (case `jc`.`jcard_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` when 'jual_lunas' then `m5`.`dpiutang_tanggal` end) AS `tgl_transaksi`,`jc`.`jcard_transaksi` AS `jcard_transaksi`,`jc`.`jcard_stat_dok` AS `jcard_stat_dok`,`jc`.`jcard_ref` AS `jcard_ref`,sum(`jc`.`jcard_nilai`) AS `jcard_nilai` from (((((`jual_card` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_kwitansi')))) left join `detail_lunas_piutang` `m5` on(((`m5`.`dpiutang_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_lunas')))) group by (case `jc`.`jcard_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jcard_transaksi`,`jc`.`jcard_ref`,`jc`.`jcard_stat_dok`;



CREATE OR REPLACE VIEW `vu_sum_jual_cek` AS select (case `jc`.`jcek_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` when 'jual_lunas' then `m5`.`dpiutang_tanggal` end) AS `tgl_transaksi`,`jc`.`jcek_transaksi` AS `jcek_transaksi`,`jc`.`jcek_stat_dok` AS `jcek_stat_dok`,`jc`.`jcek_ref` AS `jcek_ref`,sum(`jc`.`jcek_nilai`) AS `jcek_nilai` from (((((`jual_cek` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_kwitansi')))) left join `detail_lunas_piutang` `m5` on(((`m5`.`dpiutang_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_lunas')))) group by (case `jc`.`jcek_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jcek_transaksi`,`jc`.`jcek_ref`,`jc`.`jcek_stat_dok`;



CREATE OR REPLACE VIEW `vu_sum_jual_kwitansi` AS select (case `jc`.`jkwitansi_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` when 'jual_lunas' then `m5`.`dpiutang_tanggal` end) AS `tgl_transaksi`,`jc`.`jkwitansi_transaksi` AS `jkwitansi_transaksi`,`jc`.`jkwitansi_stat_dok` AS `jkwitansi_stat_dok`,`jc`.`jkwitansi_ref` AS `jkwitansi_ref`,sum(`jc`.`jkwitansi_nilai`) AS `jkwitansi_nilai` from (((((`jual_kwitansi` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_kwitansi')))) left join `detail_lunas_piutang` `m5` on(((`m5`.`dpiutang_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_lunas')))) group by (case `jc`.`jkwitansi_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jkwitansi_transaksi`,`jc`.`jkwitansi_ref`,`jc`.`jkwitansi_stat_dok`;



CREATE OR REPLACE VIEW `vu_sum_jual_transfer` AS select (case `jc`.`jtransfer_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` when 'jual_lunas' then `m5`.`dpiutang_tanggal` end) AS `tgl_transaksi`,`jc`.`jtransfer_transaksi` AS `jtransfer_transaksi`,`jc`.`jtransfer_stat_dok` AS `jtransfer_stat_dok`,`jc`.`jtransfer_ref` AS `jtransfer_ref`,sum(`jc`.`jtransfer_nilai`) AS `jtransfer_nilai` from (((((`jual_transfer` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_kwitansi')))) left join `detail_lunas_piutang` `m5` on(((`m5`.`dpiutang_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_lunas')))) group by (case `jc`.`jtransfer_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jtransfer_transaksi`,`jc`.`jtransfer_ref`,`jc`.`jtransfer_stat_dok`;



CREATE OR REPLACE VIEW `vu_sum_jual_tunai` AS select (case `jc`.`jtunai_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` when 'jual_lunas' then `m5`.`dpiutang_tanggal` end) AS `tgl_transaksi`,`jc`.`jtunai_transaksi` AS `jtunai_transaksi`,`jc`.`jtunai_ref` AS `jtunai_ref`,`jc`.`jtunai_stat_dok` AS `jtunai_stat_dok`,sum(`jc`.`jtunai_nilai`) AS `jtunai_nilai` from (((((`jual_tunai` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_kwitansi')))) left join `detail_lunas_piutang` `m5` on(((`m5`.`dpiutang_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_lunas')))) group by (case `jc`.`jtunai_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jtunai_transaksi`,`jc`.`jtunai_ref`,`jc`.`jtunai_stat_dok`;

