ALTER TABLE `jual_cek` CHANGE `jcek_bank` `jcek_bank` INT( 11 ) NOT NULL DEFAULT '0';

DROP VIEW IF EXISTS `vu_total_jual_produk_group`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY INVOKER VIEW `vu_total_jual_produk_group` AS select ifnull(sum(`miracledb`.`detail_jual_produk`.`dproduk_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`miracledb`.`detail_jual_produk`.`dproduk_harga` * `miracledb`.`detail_jual_produk`.`dproduk_jumlah`) * (100 - `miracledb`.`detail_jual_produk`.`dproduk_diskon`)) / 100)),0) AS `total_nilai`,`miracledb`.`detail_jual_produk`.`dproduk_master` AS `dproduk_master` from `detail_jual_produk` group by `miracledb`.`detail_jual_produk`.`dproduk_master`;

DROP VIEW IF EXISTS `vu_trans_produk`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_trans_produk` AS select `miracledb`.`master_jual_produk`.`jproduk_nobukti` AS `no_bukti`,`miracledb`.`master_jual_produk`.`jproduk_cust` AS `cust_id`,`miracledb`.`master_jual_produk`.`jproduk_tanggal` AS `tanggal`,ifnull(`vu_total_jual_produk_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_produk_group`.`total_nilai`,0) AS `total_nilai`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota` from ((`master_jual_produk` left join `vu_total_jual_produk_group` on((`vu_total_jual_produk_group`.`dproduk_master` = `miracledb`.`master_jual_produk`.`jproduk_id`))) join `vu_customer` on((`miracledb`.`master_jual_produk`.`jproduk_cust` = `vu_customer`.`cust_id`)));

DROP VIEW IF EXISTS `vu_total_jual_rawat_group`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY INVOKER VIEW `vu_total_jual_rawat_group` AS select ifnull(sum(`miracledb`.`detail_jual_rawat`.`drawat_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`miracledb`.`detail_jual_rawat`.`drawat_harga` * `miracledb`.`detail_jual_rawat`.`drawat_jumlah`) * (100 - `miracledb`.`detail_jual_rawat`.`drawat_diskon`)) / 100)),0) AS `total_nilai`,`miracledb`.`detail_jual_rawat`.`drawat_master` AS `drawat_master` from `detail_jual_rawat` group by `miracledb`.`detail_jual_rawat`.`drawat_master`;

DROP VIEW IF EXISTS `vu_trans_rawat`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY INVOKER VIEW `vu_trans_rawat` AS select `miracledb`.`master_jual_rawat`.`jrawat_nobukti` AS `no_bukti`,`miracledb`.`master_jual_rawat`.`jrawat_cust` AS `cust_id`,`miracledb`.`master_jual_rawat`.`jrawat_tanggal` AS `tanggal`,ifnull(`vu_total_jual_rawat_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_rawat_group`.`total_nilai`,0) AS `total_nilai`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota` from ((`master_jual_rawat` left join `vu_total_jual_rawat_group` on((`vu_total_jual_rawat_group`.`drawat_master` = `miracledb`.`master_jual_rawat`.`jrawat_id`))) join `vu_customer` on((`miracledb`.`master_jual_rawat`.`jrawat_cust` = `vu_customer`.`cust_id`)));

DROP VIEW IF EXISTS `vu_total_jual_paket_group`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY INVOKER VIEW `vu_total_jual_paket_group` AS select ifnull(sum(`miracledb`.`detail_jual_paket`.`dpaket_jumlah`),0) AS `jumlah_barang`,ifnull(sum((((`miracledb`.`detail_jual_paket`.`dpaket_harga` * `miracledb`.`detail_jual_paket`.`dpaket_jumlah`) * (100 - `miracledb`.`detail_jual_paket`.`dpaket_diskon`)) / 100)),0) AS `total_nilai`,`miracledb`.`detail_jual_paket`.`dpaket_master` AS `dpaket_master` from `detail_jual_paket` group by `miracledb`.`detail_jual_paket`.`dpaket_master`;

DROP VIEW IF EXISTS `vu_trans_paket`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY INVOKER VIEW `vu_trans_paket` AS select `miracledb`.`master_jual_paket`.`jpaket_nobukti` AS `no_bukti`,`miracledb`.`master_jual_paket`.`jpaket_cust` AS `cust_id`,`miracledb`.`master_jual_paket`.`jpaket_tanggal` AS `tanggal`,ifnull(`vu_total_jual_paket_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_paket_group`.`total_nilai`,0) AS `total_nilai`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota` from ((`master_jual_paket` left join `vu_total_jual_paket_group` on((`vu_total_jual_paket_group`.`dpaket_master` = `miracledb`.`master_jual_paket`.`jpaket_id`))) join `vu_customer` on((`miracledb`.`master_jual_paket`.`jpaket_cust` = `vu_customer`.`cust_id`)));

DROP VIEW IF EXISTS `vu_trans_union`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_trans_union` AS select `vu_trans_produk`.`no_bukti` AS `no_bukti`,`vu_trans_produk`.`cust_id` AS `cust_id`,`vu_trans_produk`.`tanggal` AS `tanggal`,`vu_trans_produk`.`jumlah_barang` AS `jumlah_barang`,`vu_trans_produk`.`total_nilai` AS `total_nilai`,`vu_trans_produk`.`cust_no` AS `cust_no`,`vu_trans_produk`.`cust_member` AS `cust_member`,`vu_trans_produk`.`cust_nama` AS `cust_nama`,`vu_trans_produk`.`cust_kelamin` AS `cust_kelamin`,`vu_trans_produk`.`cust_alamat` AS `cust_alamat`,`vu_trans_produk`.`cust_kota` AS `cust_kota` from `vu_trans_produk` union select `vu_trans_rawat`.`no_bukti` AS `no_bukti`,`vu_trans_rawat`.`cust_id` AS `cust_id`,`vu_trans_rawat`.`tanggal` AS `tanggal`,`vu_trans_rawat`.`jumlah_barang` AS `jumlah_barang`,`vu_trans_rawat`.`total_nilai` AS `total_nilai`,`vu_trans_rawat`.`cust_no` AS `cust_no`,`vu_trans_rawat`.`cust_member` AS `cust_member`,`vu_trans_rawat`.`cust_nama` AS `cust_nama`,`vu_trans_rawat`.`cust_kelamin` AS `cust_kelamin`,`vu_trans_rawat`.`cust_alamat` AS `cust_alamat`,`vu_trans_rawat`.`cust_kota` AS `cust_kota` from `vu_trans_rawat` union select `vu_trans_paket`.`no_bukti` AS `no_bukti`,`vu_trans_paket`.`cust_id` AS `cust_id`,`vu_trans_paket`.`tanggal` AS `tanggal`,`vu_trans_paket`.`jumlah_barang` AS `jumlah_barang`,`vu_trans_paket`.`total_nilai` AS `total_nilai`,`vu_trans_paket`.`cust_no` AS `cust_no`,`vu_trans_paket`.`cust_member` AS `cust_member`,`vu_trans_paket`.`cust_nama` AS `cust_nama`,`vu_trans_paket`.`cust_kelamin` AS `cust_kelamin`,`vu_trans_paket`.`cust_alamat` AS `cust_alamat`,`vu_trans_paket`.`cust_kota` AS `cust_kota` from `vu_trans_paket`;