ALTER TABLE `detail_jual_paket` ADD `dpaket_sisa_paket` TINYINT(4) NOT NULL DEFAULT 0 AFTER `dpaket_jumlah`;

ALTER TABLE `master_ambil_paket` ADD `apaket_item` INT(11) NULL DEFAULT NULL AFTER `apaket_revised`,
ADD `apaket_jenis_item` ENUM('perawatan','produk') NULL DEFAULT NULL AFTER `apaket_item`,
ADD `apaket_sisa_item` TINYINT(4) NOT NULL DEFAULT 0 AFTER `apaket_jenis_item`;

ALTER TABLE `detail_ambil_paket` ADD `dapaket_jpaket` INT NOT NULL AFTER `dapaket_master` ,
ADD `dapaket_paket` INT NOT NULL AFTER `dapaket_jpaket` ;

ALTER TABLE `detail_ambil_paket` CHANGE `dapaket_jenis` `dapaket_jenis_item` ENUM( 'produk', 'perawatan' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL ;

ALTER TABLE `detail_ambil_paket` DROP `dapaket_master` ,
DROP `dapaket_sapaket` ,
DROP `dapaket_nama` ;

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_cust_punya_paket` AS select `master_ambil_paket`.`apaket_id` AS `apaket_id`,`pengguna_paket`.`ppaket_cust` AS `ppaket_cust`,`submaster_apaket_item`.`sapaket_id` AS `sapaket_id`,`submaster_apaket_item`.`sapaket_item` AS `sapaket_item`,`submaster_apaket_item`.`sapaket_jenis_item` AS `sapaket_jenis_item`,`master_ambil_paket`.`apaket_sisa_paket` AS `apaket_sisa_paket`,`submaster_apaket_item`.`sapaket_sisa_item` AS `sapaket_sisa_item` from (`submaster_apaket_item` left join (`pengguna_paket` left join `master_ambil_paket` on((`pengguna_paket`.`ppaket_master` = `master_ambil_paket`.`apaket_jpaket`))) on((`submaster_apaket_item`.`sapaket_master` = `master_ambil_paket`.`apaket_id`)));

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_pengguna_paket` AS select `pengguna_paket`.`ppaket_cust` AS `ppaket_cust`,`paket_isi_perawatan`.`rpaket_master` AS `rpaket_master`,`detail_jual_paket`.`dpaket_id` AS `dpaket_id`,`detail_jual_paket`.`dpaket_master` AS `dpaket_master`,`detail_jual_paket`.`dpaket_paket` AS `dpaket_paket`,`paket_isi_perawatan`.`rpaket_perawatan` AS `rpaket_perawatan`,`paket_isi_perawatan`.`rpaket_jumlah` AS `rpaket_jumlah` from ((`detail_jual_paket` join `paket_isi_perawatan` on((`paket_isi_perawatan`.`rpaket_master` = `detail_jual_paket`.`dpaket_paket`))) left join `pengguna_paket` on((`pengguna_paket`.`ppaket_master` = `detail_jual_paket`.`dpaket_master`)));

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_detail_ambil_paket` AS select `detail_ambil_paket`.`dapaket_jpaket` AS `dapaket_jpaket`,`detail_ambil_paket`.`dapaket_dpaket` AS `dapaket_dpaket`,`detail_ambil_paket`.`dapaket_paket` AS `dapaket_paket`,`detail_ambil_paket`.`dapaket_item` AS `dapaket_item`,sum(`detail_ambil_paket`.`dapaket_jumlah`) AS `total_ambil_item` from `detail_ambil_paket` group by `detail_ambil_paket`.`dapaket_item`,`detail_ambil_paket`.`dapaket_jpaket`,`detail_ambil_paket`.`dapaket_dpaket`,`detail_ambil_paket`.`dapaket_paket`;

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_total_sisa_item_perawatan` AS select `vu_pengguna_paket`.`ppaket_cust` AS `ppaket_cust`,`vu_pengguna_paket`.`dpaket_id` AS `dpaket_id`,`vu_pengguna_paket`.`dpaket_master` AS `dpaket_master`,`vu_pengguna_paket`.`dpaket_paket` AS `dpaket_paket`,`vu_pengguna_paket`.`rpaket_perawatan` AS `rpaket_perawatan`,`vu_pengguna_paket`.`rpaket_jumlah` AS `rpaket_jumlah`,`vu_detail_ambil_paket`.`total_ambil_item` AS `total_ambil_item`,(`vu_pengguna_paket`.`rpaket_jumlah` - if((`vu_detail_ambil_paket`.`total_ambil_item` <> 'null'),`vu_detail_ambil_paket`.`total_ambil_item`,0)) AS `total_sisa_item` from (`vu_pengguna_paket` left join `vu_detail_ambil_paket` on(((`vu_pengguna_paket`.`dpaket_paket` = `vu_detail_ambil_paket`.`dapaket_paket`) and (`vu_pengguna_paket`.`rpaket_perawatan` = `vu_detail_ambil_paket`.`dapaket_item`))));

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_total_isi_paket` AS select `vu_pengguna_paket`.`dpaket_id` AS `dpaket_id`,`vu_pengguna_paket`.`dpaket_master` AS `dpaket_master`,`vu_pengguna_paket`.`dpaket_paket` AS `dpaket_paket`,sum(`vu_pengguna_paket`.`rpaket_jumlah`) AS `total_isi_paket` from `vu_pengguna_paket` group by `vu_pengguna_paket`.`dpaket_id`,`vu_pengguna_paket`.`dpaket_master`,`vu_pengguna_paket`.`dpaket_paket`;

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_total_ambil_paket` AS select `vu_detail_ambil_paket`.`dapaket_dpaket` AS `dapaket_dpaket`,`vu_detail_ambil_paket`.`dapaket_jpaket` AS `dapaket_jpaket`,`vu_detail_ambil_paket`.`dapaket_paket` AS `dapaket_paket`,sum(`vu_detail_ambil_paket`.`total_ambil_item`) AS `total_ambil_paket` from `vu_detail_ambil_paket` group by `vu_detail_ambil_paket`.`dapaket_dpaket`,`vu_detail_ambil_paket`.`dapaket_jpaket`,`vu_detail_ambil_paket`.`dapaket_paket`;

CREATE OR REPLACE ALGORITHM=MERGE DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `vu_tindakan` AS select `tindakan`.`trawat_id` AS `trawat_id`,`tindakan`.`trawat_cust` AS `trawat_cust`,`tindakan`.`trawat_keterangan` AS `trawat_keterangan`,`tindakan`.`trawat_creator` AS `trawat_creator`,`tindakan`.`trawat_update` AS `trawat_update`,`tindakan`.`trawat_date_update` AS `trawat_date_update`,`tindakan`.`trawat_revised` AS `trawat_revised`,`customer`.`cust_nama` AS `cust_nama`,`customer`.`cust_no` AS `cust_no`,`tindakan_detail`.`dtrawat_id` AS `dtrawat_id`,`tindakan_detail`.`dtrawat_perawatan` AS `dtrawat_perawatan`,`tindakan_detail`.`dtrawat_jam` AS `dtrawat_jam`,`tindakan_detail`.`dtrawat_tglapp` AS `dtrawat_tglapp`,`tindakan_detail`.`dtrawat_status` AS `dtrawat_status`,`tindakan_detail`.`dtrawat_keterangan` AS `dtrawat_keterangan`,`tindakan_detail`.`dtrawat_dapp` AS `dtrawat_dapp`,`tindakan_detail`.`dtrawat_master` AS `dtrawat_master`,`tindakan_detail`.`dtrawat_petugas2` AS `dtrawat_petugas2`,`tindakan_detail`.`dtrawat_ambil_paket` AS `dtrawat_ambil_paket`,if((`tindakan_detail`.`dtrawat_locked` = 0),'Terbuka','Tertutup') AS `dtrawat_edit`,`perawatan`.`rawat_nama` AS `rawat_nama`,`perawatan`.`rawat_harga` AS `rawat_harga`,`perawatan`.`rawat_du` AS `rawat_du`,`perawatan`.`rawat_dm` AS `rawat_dm`,`dokter`.`karyawan_nama` AS `dokter_nama`,`dokter`.`karyawan_id` AS `dokter_id`,`dokter`.`karyawan_username` AS `dokter_username`,`terapis`.`karyawan_nama` AS `terapis_nama`,`terapis`.`karyawan_id` AS `terapis_id`,`terapis`.`karyawan_username` AS `terapis_username`,`kategori`.`kategori_nama` AS `kategori_nama`,if((`vu_total_sisa_item_perawatan`.`total_sisa_item` > 0),'ada','tidak ada') AS `cust_punya_paket`,`vu_total_sisa_item_perawatan`.`total_sisa_item` AS `total_sisa_item`,`vu_total_sisa_item_perawatan`.`dpaket_id` AS `dpaket_id`,`vu_total_sisa_item_perawatan`.`dpaket_master` AS `dpaket_master`,`vu_total_sisa_item_perawatan`.`dpaket_paket` AS `dpaket_paket` from (((((((`tindakan` join `customer` on((`tindakan`.`trawat_cust` = `customer`.`cust_id`))) join `tindakan_detail` on((`tindakan_detail`.`dtrawat_master` = `tindakan`.`trawat_id`))) left join `perawatan` on((`tindakan_detail`.`dtrawat_perawatan` = `perawatan`.`rawat_id`))) left join `karyawan` `dokter` on((`tindakan_detail`.`dtrawat_petugas1` = `dokter`.`karyawan_id`))) left join `karyawan` `terapis` on((`tindakan_detail`.`dtrawat_petugas2` = `terapis`.`karyawan_id`))) left join `kategori` on((`perawatan`.`rawat_kategori` = `kategori`.`kategori_id`))) left join `vu_total_sisa_item_perawatan` on(((`vu_total_sisa_item_perawatan`.`ppaket_cust` = `tindakan`.`trawat_cust`) and (`vu_total_sisa_item_perawatan`.`rpaket_perawatan` = `tindakan_detail`.`dtrawat_perawatan`))));