
--- VIEW DETAIL JUAL PERAWATAN

CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vu_detail_jual_rawat` AS select `detail_jual_rawat`.`drawat_master` AS `drawat_master`,`detail_jual_rawat`.`drawat_rawat` AS `drawat_rawat`,`vu_perawatan`.`rawat_nama` AS `produk_nama`,`vu_perawatan`.`kategori2_nama` AS `kategori2_nama`,`vu_perawatan`.`kategori_nama` AS `kategori_nama`,`vu_perawatan`.`jenis_nama` AS `jenis_nama`,`detail_jual_rawat`.`drawat_jumlah` AS `jumlah_barang`,`detail_jual_rawat`.`drawat_harga` AS `harga_satuan`,`detail_jual_rawat`.`drawat_diskon` AS `drawat_diskon`,`detail_jual_rawat`.`drawat_diskon_jenis` AS `diskon_jenis`,`detail_jual_rawat`.`drawat_sales` AS `sales`,`master_jual_rawat`.`jrawat_nobukti` AS `no_bukti`,`master_jual_rawat`.`jrawat_cust` AS `jrawat_cust`,`customer`.`cust_member` AS `cust_member`,`customer`.`cust_nama` AS `cust_nama`,`customer`.`cust_no` AS `cust_no`,`customer`.`cust_kelamin` AS `cust_kelamin`,`customer`.`cust_alamat` AS `cust_alamat`,`customer`.`cust_kota` AS `cust_kota`,`vu_perawatan`.`rawat_kode` AS `produk_kode`,_utf8'paket' AS `satuan_nama`,`detail_jual_rawat`.`drawat_diskon` AS `diskon`,(((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) * `detail_jual_rawat`.`drawat_diskon`) / 100) AS `diskon_nilai`,((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) - (((`detail_jual_rawat`.`drawat_harga` * `detail_jual_rawat`.`drawat_jumlah`) * `detail_jual_rawat`.`drawat_diskon`) / 100)) AS `subtotal`,`master_jual_rawat`.`jrawat_tanggal` AS `tanggal` from (((`detail_jual_rawat` join `vu_perawatan` on((`vu_perawatan`.`rawat_id` = `detail_jual_rawat`.`drawat_rawat`))) join `master_jual_rawat` on((`detail_jual_rawat`.`drawat_master` = `master_jual_rawat`.`jrawat_id`))) join `customer` on((`master_jual_rawat`.`jrawat_cust` = `customer`.`cust_id`)));

--
-- Structure for view `vu_trans_rawat`
--

CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vu_trans_rawat` AS select `master_jual_rawat`.`jrawat_nobukti` AS `no_bukti`,`master_jual_rawat`.`jrawat_cust` AS `cust_id`,`master_jual_rawat`.`jrawat_tanggal` AS `tanggal`,`vu_customer`.`cust_no` AS `cust_no`,`vu_customer`.`cust_member` AS `cust_member`,`vu_customer`.`cust_nama` AS `cust_nama`,`vu_customer`.`cust_kelamin` AS `cust_kelamin`,`vu_customer`.`cust_alamat` AS `cust_alamat`,`vu_customer`.`cust_kota` AS `cust_kota`,ifnull(`vu_total_jual_rawat_group`.`jumlah_barang`,0) AS `jumlah_barang`,ifnull(`vu_total_jual_rawat_group`.`total_nilai`,0) AS `total_nilai`,ifnull(`master_jual_rawat`.`jrawat_diskon`,0) AS `diskon`,ifnull(`master_jual_rawat`.`jrawat_cashback`,0) AS `cashback`,ifnull(`jual_kredit`.`jkredit_nilai`,0) AS `kredit`,ifnull(`jual_cek`.`jcek_nilai`,0) AS `cek`,ifnull(`jual_card`.`jcard_nilai`,0) AS `card`,ifnull(`jual_kwitansi`.`jkwitansi_nilai`,0) AS `kuintansi`,ifnull(`jual_transfer`.`jtransfer_nilai`,0) AS `transfer`,ifnull(`jual_tunai`.`jtunai_nilai`,0) AS `tunai` from ((((((((`master_jual_rawat` left join `vu_total_jual_rawat_group` on((`vu_total_jual_rawat_group`.`drawat_master` = `master_jual_rawat`.`jrawat_id`))) left join `vu_customer` on((`master_jual_rawat`.`jrawat_cust` = `vu_customer`.`cust_id`))) left join `jual_card` on((`jual_card`.`jcard_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_cek` on((`jual_cek`.`jcek_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_kredit` on((`jual_kredit`.`jkredit_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_kwitansi` on((`jual_kwitansi`.`jkwitansi_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_transfer` on((`jual_transfer`.`jtransfer_ref` = `master_jual_rawat`.`jrawat_nobukti`))) left join `jual_tunai` on((`jual_tunai`.`jtunai_ref` = `master_jual_rawat`.`jrawat_nobukti`)));
