CREATE OR REPLACE VIEW `vu_kasbank_detail` AS select `kasbank`.`kasbank_id` AS `kasbank_id`,`kasbank`.`kasbank_tanggal` AS `kasbank_tanggal`,`kasbank`.`kasbank_nobukti` AS `kasbank_nobukti`,`kasbank`.`kasbank_akun` AS `kasbank_akun`,`kasbank`.`kasbank_terimauntuk` AS `kasbank_terimauntuk`,`kasbank`.`kasbank_jenis` AS `kasbank_jenis`,`kasbank`.`kasbank_noref` AS `kasbank_noref`,`kasbank`.`kasbank_keterangan` AS `kasbank_keterangan`,`kasbank`.`kasbank_author` AS `kasbank_author`,`kasbank`.`kasbank_date_create` AS `kasbank_date_create`,`kasbank`.`kasbank_update` AS `kasbank_update`,`kasbank`.`kasbank_date_update` AS `kasbank_date_update`,`kasbank`.`kasbank_post` AS `kasbank_post`,`kasbank`.`kasbank_date_post` AS `kasbank_date_post`,`kasbank`.`kasbank_revised` AS `kasbank_revised`,`kasbank_detail`.`dkasbank_id` AS `dkasbank_id`,`kasbank_detail`.`dkasbank_master` AS `dkasbank_master`,`kasbank_detail`.`dkasbank_akun` AS `dkasbank_akun`,`kasbank_detail`.`dkasbank_detail` AS `dkasbank_detail`,`kasbank_detail`.`dkasbank_debet` AS `dkasbank_debet`,`kasbank_detail`.`dkasbank_kredit` AS `dkasbank_kredit`,`kasbank`.`kasbank_arsip` AS `kasbank_arsip`,`akun`.`akun_kode` AS `akun_kode`,`akun`.`akun_jenis` AS `akun_jenis`,`akun`.`akun_parent` AS `akun_parent`,`akun`.`akun_level` AS `akun_level`,`akun`.`akun_nama` AS `akun_nama`,`kasbank_detail`.`dkasbank_id` AS `kasbank_detail_id` from ((`kasbank` join `kasbank_detail` on((`kasbank`.`kasbank_id` = `kasbank_detail`.`dkasbank_master`))) join `akun` on((`akun`.`akun_id` = `kasbank_detail`.`dkasbank_akun`)));


CREATE OR REPLACE VIEW `vu_jurnal_bank` AS select `vu_kasbank`.`kasbank_id` AS `kasbank_id`,`vu_kasbank`.`kasbank_tanggal` AS `tanggal`,`vu_kasbank`.`kasbank_nobukti` AS `no_jurnal`,`vu_kasbank`.`kasbank_akun` AS `akun`,`vu_kasbank`.`akun_kode` AS `akun_kode`,`vu_kasbank`.`akun_nama` AS `akun_nama`,`vu_kasbank`.`kasbank_terimauntuk` AS `terimauntuk`,`vu_kasbank`.`kasbank_jenis` AS `jenis`,`vu_kasbank`.`kasbank_noref` AS `noref`,`vu_kasbank`.`kasbank_keterangan` AS `keterangan`,`vu_kasbank`.`kasbank_debet` AS `debet`,`vu_kasbank`.`kasbank_kredit` AS `kredit`,`vu_kasbank`.`kasbank_post` AS `post`,`vu_kasbank`.`kasbank_date_post` AS `post_date`,`vu_kasbank`.`kasbank_arsip` AS `kasbank_arsip`,1 AS `kasbank_detail_id` from `vu_kasbank` union select `vu_kasbank_detail`.`kasbank_id` AS `kasbank_id`,`vu_kasbank_detail`.`kasbank_tanggal` AS `tanggal`,`vu_kasbank_detail`.`kasbank_nobukti` AS `no_jurnal`,`vu_kasbank_detail`.`dkasbank_akun` AS `akun`,`vu_kasbank_detail`.`akun_kode` AS `akun_kode`,`vu_kasbank_detail`.`akun_nama` AS `akun_nama`,`vu_kasbank_detail`.`kasbank_terimauntuk` AS `terimauntuk`,`vu_kasbank_detail`.`kasbank_jenis` AS `jenis`,`vu_kasbank_detail`.`kasbank_noref` AS `noref`,`vu_kasbank_detail`.`dkasbank_detail` AS `keterangan`,`vu_kasbank_detail`.`dkasbank_debet` AS `debet`,`vu_kasbank_detail`.`dkasbank_kredit` AS `kredit`,`vu_kasbank_detail`.`kasbank_post` AS `post`,`vu_kasbank_detail`.`kasbank_date_post` AS `post_date`,`vu_kasbank_detail`.`kasbank_arsip` AS `kasbank_arsip`,`vu_kasbank_detail`.`kasbank_detail_id` AS `kasbank_detail_id` from `vu_kasbank_detail`;


CREATE OR REPLACE VIEW `vu_kasbank_group` AS select `kasbank_detail`.`dkasbank_master` AS `kasbank_master`,ifnull(sum(`kasbank_detail`.`dkasbank_debet`),0) AS `kasbank_debet`,ifnull(sum(`kasbank_detail`.`dkasbank_kredit`),0) AS `kasbank_kredit`,`kasbank_detail`.`dkasbank_id` AS `kasbank_detail_id` from `kasbank_detail` group by `kasbank_detail`.`dkasbank_master`;


CREATE OR REPLACE VIEW `vu_kasbank` AS select `kasbank`.`kasbank_id` AS `kasbank_id`,`kasbank`.`kasbank_tanggal` AS `kasbank_tanggal`,`kasbank`.`kasbank_nobukti` AS `kasbank_nobukti`,`kasbank`.`kasbank_akun` AS `kasbank_akun`,`kasbank`.`kasbank_terimauntuk` AS `kasbank_terimauntuk`,`kasbank`.`kasbank_jenis` AS `kasbank_jenis`,`kasbank`.`kasbank_noref` AS `kasbank_noref`,`kasbank`.`kasbank_keterangan` AS `kasbank_keterangan`,`kasbank`.`kasbank_author` AS `kasbank_author`,`kasbank`.`kasbank_date_create` AS `kasbank_date_create`,`kasbank`.`kasbank_update` AS `kasbank_update`,`kasbank`.`kasbank_date_update` AS `kasbank_date_update`,`kasbank`.`kasbank_post` AS `kasbank_post`,`kasbank`.`kasbank_date_post` AS `kasbank_date_post`,`kasbank`.`kasbank_revised` AS `kasbank_revised`,`vu_kasbank_group`.`kasbank_debet` AS `kasbank_kredit`,`vu_kasbank_group`.`kasbank_kredit` AS `kasbank_debet`,`akun`.`akun_kode` AS `akun_kode`,`akun`.`akun_nama` AS `akun_nama`,`akun`.`akun_level` AS `akun_level`,`akun`.`akun_jenis` AS `akun_jenis`,`kasbank`.`kasbank_arsip` AS `kasbank_arsip`,`vu_kasbank_group`.`kasbank_detail_id` AS `kasbank_detail_id` from ((`kasbank` join `vu_kasbank_group` on((`kasbank`.`kasbank_id` = `vu_kasbank_group`.`kasbank_master`))) join `akun` on((`kasbank`.`kasbank_akun` = `akun`.`akun_id`)));
