ALTER TABLE `cetak_kwitansi`  ADD INDEX `kwitansi_no` (`kwitansi_no`);


CREATE or REPLACE VIEW `vu_sum_jual_card` AS select (case `jc`.`jcard_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end) AS `tgl_transaksi`,`jc`.`jcard_transaksi` AS `jcard_transaksi`,`jc`.`jcard_stat_dok` AS `jcard_stat_dok`,`jc`.`jcard_ref` AS `jcard_ref`,sum(`jc`.`jcard_nilai`) AS `jcard_nilai` from ((((`jual_card` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jcard_ref`) and (`jc`.`jcard_transaksi` = 'jual_kwitansi')))) group by (case `jc`.`jcard_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jcard_transaksi`,`jc`.`jcard_ref`,`jc`.`jcard_stat_dok`;


CREATE OR REPLACE VIEW `vu_sum_jual_cek` AS select (case `jc`.`jcek_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end) AS `tgl_transaksi`,`jc`.`jcek_transaksi` AS `jcek_transaksi`,`jc`.`jcek_stat_dok` AS `jcek_stat_dok`,`jc`.`jcek_ref` AS `jcek_ref`,sum(`jc`.`jcek_nilai`) AS `jcek_nilai` from ((((`jual_cek` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jcek_ref`) and (`jc`.`jcek_transaksi` = 'jual_kwitansi')))) group by (case `jc`.`jcek_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jcek_transaksi`,`jc`.`jcek_ref`,`jc`.`jcek_stat_dok`;


CREATE OR REPLACE VIEW `vu_sum_jual_kwitansi` AS select (case `jc`.`jkwitansi_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end) AS `tgl_transaksi`,`jc`.`jkwitansi_transaksi` AS `jkwitansi_transaksi`,`jc`.`jkwitansi_stat_dok` AS `jkwitansi_stat_dok`,`jc`.`jkwitansi_ref` AS `jkwitansi_ref`,sum(`jc`.`jkwitansi_nilai`) AS `jkwitansi_nilai` from ((((`jual_kwitansi` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jkwitansi_ref`) and (`jc`.`jkwitansi_transaksi` = 'jual_kwitansi')))) group by (case `jc`.`jkwitansi_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jkwitansi_transaksi`,`jc`.`jkwitansi_ref`,`jc`.`jkwitansi_stat_dok`;


CREATE OR REPLACE VIEW `vu_sum_jual_transfer` AS select (case `jc`.`jtransfer_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end) AS `tgl_transaksi`,`jc`.`jtransfer_transaksi` AS `jtransfer_transaksi`,`jc`.`jtransfer_stat_dok` AS `jtransfer_stat_dok`,`jc`.`jtransfer_ref` AS `jtransfer_ref`,sum(`jc`.`jtransfer_nilai`) AS `jtransfer_nilai` from ((((`jual_transfer` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jtransfer_ref`) and (`jc`.`jtransfer_transaksi` = 'jual_kwitansi')))) group by (case `jc`.`jtransfer_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jtransfer_transaksi`,`jc`.`jtransfer_ref`,`jc`.`jtransfer_stat_dok`;


CREATE OR REPLACE VIEW  `vu_sum_jual_tunai` AS select (case `jc`.`jtunai_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end) AS `tgl_transaksi`,`jc`.`jtunai_transaksi` AS `jtunai_transaksi`,`jc`.`jtunai_ref` AS `jtunai_ref`,`jc`.`jtunai_stat_dok` AS `jtunai_stat_dok`,sum(`jc`.`jtunai_nilai`) AS `jtunai_nilai` from ((((`jual_tunai` `jc` left join `master_jual_produk` `m1` on(((`m1`.`jproduk_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_produk')))) left join `master_jual_rawat` `m2` on(((`m2`.`jrawat_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_rawat')))) left join `master_jual_paket` `m3` on(((`m3`.`jpaket_nobukti` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_paket')))) left join `cetak_kwitansi` `m4` on(((`m4`.`kwitansi_no` = `jc`.`jtunai_ref`) and (`jc`.`jtunai_transaksi` = 'jual_kwitansi')))) group by (case `jc`.`jtunai_transaksi` when 'jual_produk' then `m1`.`jproduk_tanggal` when 'jual_rawat' then `m2`.`jrawat_tanggal` when 'jual_paket' then `m3`.`jpaket_tanggal` when 'jual_kwitansi' then `m4`.`kwitansi_tanggal` end),`jc`.`jtunai_transaksi`,`jc`.`jtunai_ref`,`jc`.`jtunai_stat_dok`;


CREATE OR REPLACE VIEW  `vu_sum_jual_voucher` AS select date_format(`voucher_terima`.`tvoucher_date_create`,'%Y-%m-%d') AS `tvoucher_date_create`,`voucher_terima`.`tvoucher_transaksi` AS `tvoucher_transaksi`,`voucher_terima`.`tvoucher_stat_dok` AS `tvoucher_stat_dok`,`voucher_terima`.`tvoucher_ref` AS `tvoucher_ref`,sum(`voucher_terima`.`tvoucher_nilai`) AS `tvoucher_nilai` from `voucher_terima` group by date_format(`voucher_terima`.`tvoucher_date_create`,'%Y-%m-%d'),`voucher_terima`.`tvoucher_transaksi`,`voucher_terima`.`tvoucher_ref`,`voucher_terima`.`tvoucher_stat_dok`;


CREATE OR REPLACE VIEW  `vu_trans_terima_jual` AS select `vu_sum_jual_tunai`.`jtunai_transaksi` AS `jenis_transaksi`,date_format(`vu_sum_jual_tunai`.`tgl_transaksi`,_utf8'%Y-%m-%d') AS `tanggal`,`vu_sum_jual_tunai`.`jtunai_ref` AS `no_ref`,`vu_sum_jual_tunai`.`jtunai_nilai` AS `nilai_tunai`,0 AS `nilai_card`,0 AS `nilai_cek`,0 AS `nilai_transfer`,0 AS `nilai_kwitansi`,0 AS `nilai_voucher`,0 AS `nilai_kredit`,`vu_sum_jual_tunai`.`jtunai_stat_dok` AS `stat_dok` from `vu_sum_jual_tunai` union select `vu_sum_jual_card`.`jcard_transaksi` AS `jenis_transaksi`,date_format(`vu_sum_jual_card`.`tgl_transaksi`,_utf8'%Y-%m-%d') AS `tanggal`,`vu_sum_jual_card`.`jcard_ref` AS `no_ref`,0 AS `nilai_tunai`,`vu_sum_jual_card`.`jcard_nilai` AS `nilai_card`,0 AS `nilai_cek`,0 AS `nilai_transfer`,0 AS `nilai_kwitansi`,0 AS `nilai_voucher`,0 AS `nilai_kredit`,`vu_sum_jual_card`.`jcard_stat_dok` AS `stat_dok` from `vu_sum_jual_card` union select `vu_sum_jual_cek`.`jcek_transaksi` AS `jenis_transaksi`,date_format(`vu_sum_jual_cek`.`tgl_transaksi`,_utf8'%Y-%m-%d') AS `tanggal`,`vu_sum_jual_cek`.`jcek_ref` AS `no_ref`,0 AS `nilai_tunai`,0 AS `nilai_card`,`vu_sum_jual_cek`.`jcek_nilai` AS `nilai_cek`,0 AS `nilai_transfer`,0 AS `nilai_kwitansi`,0 AS `nilai_voucher`,0 AS `nilai_kredit`,`vu_sum_jual_cek`.`jcek_stat_dok` AS `stat_dok` from `vu_sum_jual_cek` union select `vu_sum_jual_transfer`.`jtransfer_transaksi` AS `jenis_transaksi`,date_format(`vu_sum_jual_transfer`.`tgl_transaksi`,_utf8'%Y-%m-%d') AS `tanggal`,`vu_sum_jual_transfer`.`jtransfer_ref` AS `no_ref`,0 AS `nilai_tunai`,0 AS `nilai_card`,0 AS `nilai_cek`,`vu_sum_jual_transfer`.`jtransfer_nilai` AS `nilai_transfer`,0 AS `nilai_kwitansi`,0 AS `nilai_voucher`,0 AS `nilai_kredit`,`vu_sum_jual_transfer`.`jtransfer_stat_dok` AS `stat_dok` from `vu_sum_jual_transfer` union select `vu_sum_jual_kwitansi`.`jkwitansi_transaksi` AS `jenis_transaksi`,date_format(`vu_sum_jual_kwitansi`.`tgl_transaksi`,_utf8'%Y-%m-%d') AS `tanggal`,`vu_sum_jual_kwitansi`.`jkwitansi_ref` AS `no_ref`,0 AS `nilai_tunai`,0 AS `nilai_card`,0 AS `nilai_cek`,0 AS `nilai_transfer`,`vu_sum_jual_kwitansi`.`jkwitansi_nilai` AS `nilai_kwitansi`,0 AS `nilai_voucher`,0 AS `nilai_kredit`,`vu_sum_jual_kwitansi`.`jkwitansi_stat_dok` AS `stat_dok` from `vu_sum_jual_kwitansi` union select `voucher_terima`.`tvoucher_transaksi` AS `jenis_transaksi`,date_format(`voucher_terima`.`tvoucher_date_create`,_utf8'%Y-%m-%d') AS `tanggal`,`voucher_terima`.`tvoucher_ref` AS `no_ref`,0 AS `nilai_tunai`,0 AS `nilai_card`,0 AS `nilai_cek`,0 AS `nilai_transfer`,0 AS `nilai_kwitansi`,`voucher_terima`.`tvoucher_nilai` AS `nilai_voucher`,0 AS `nilai_kredit`,`voucher_terima`.`tvoucher_stat_dok` AS `stat_dok` from `voucher_terima`;
