CREATE TABLE IF NOT EXISTS `absensi_bt` (
  `absensi_id` int(10) NOT NULL AUTO_INCREMENT,
  `absensi_karyawan_id` int(10) DEFAULT NULL,
  `absensi_bulan` int(10) DEFAULT NULL,
  `absensi_tahun` int(10) DEFAULT NULL,
  `absensi_shift_1` varchar(5) DEFAULT NULL,
  `absensi_shift_2` varchar(5) DEFAULT NULL,
  `absensi_shift_3` varchar(5) DEFAULT NULL,
  `absensi_shift_4` varchar(5) DEFAULT NULL,
  `absensi_shift_5` varchar(5) DEFAULT NULL,
  `absensi_shift_6` varchar(5) DEFAULT NULL,
  `absensi_shift_7` varchar(5) DEFAULT NULL,
  `absensi_shift_8` varchar(5) DEFAULT NULL,
  `absensi_shift_9` varchar(5) DEFAULT NULL,
  `absensi_shift_10` varchar(5) DEFAULT NULL,
  `absensi_shift_11` varchar(5) DEFAULT NULL,
  `absensi_shift_12` varchar(5) DEFAULT NULL,
  `absensi_shift_13` varchar(5) DEFAULT NULL,
  `absensi_shift_14` varchar(5) DEFAULT NULL,
  `absensi_shift_15` varchar(5) DEFAULT NULL,
  `absensi_shift_16` varchar(5) DEFAULT NULL,
  `absensi_shift_17` varchar(5) DEFAULT NULL,
  `absensi_shift_18` varchar(5) DEFAULT NULL,
  `absensi_shift_19` varchar(5) DEFAULT NULL,
  `absensi_shift_20` varchar(5) DEFAULT NULL,
  `absensi_shift_21` varchar(5) DEFAULT NULL,
  `absensi_shift_22` varchar(5) DEFAULT NULL,
  `absensi_shift_23` varchar(5) DEFAULT NULL,
  `absensi_shift_24` varchar(5) DEFAULT NULL,
  `absensi_shift_25` varchar(5) DEFAULT NULL,
  `absensi_shift_26` varchar(5) DEFAULT NULL,
  `absensi_shift_27` varchar(5) DEFAULT NULL,
  `absensi_shift_28` varchar(5) DEFAULT NULL,
  `absensi_shift_29` varchar(5) DEFAULT NULL,
  `absensi_shift_30` varchar(5) DEFAULT NULL,
  `absensi_shift_31` varchar(5) DEFAULT NULL,
  `absensi_keterangan` varchar(500) DEFAULT NULL,
  `absensi_creator` varchar(50) DEFAULT NULL,
  `absensi_date_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `absensi_update` varchar(50) DEFAULT NULL,
  `absensi_date_update` timestamp NULL DEFAULT NULL,
  `absensi_revised` int(11) DEFAULT NULL,
  PRIMARY KEY (`absensi_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `menus` (`menu_parent`, `menu_position`, `menu_title`, `menu_link`, `menu_leftpanel`) VALUES (7, 7, 'Absensi Terapis', '?c=c_absensi_bt', 'Y');